# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginLocal():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginLocal(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1920, 1080)
    self.driver.find_element(By.CSS_SELECTOR, ".button > span:nth-child(2)").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("tiago")
    self.driver.find_element(By.ID, "id_password").send_keys("andre123456")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    assert self.driver.find_element(By.CSS_SELECTOR, ".message-body strong").text == "Bem vindo(a) Tiago"
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > .button").click()
  
