# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEscola():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_escola(self):
    self.driver.get("http://127.0.0.1:8000/inscricoes/criar")
    self.driver.set_window_size(1918, 1027)
    self.driver.find_element(By.NAME, "escola-dia").click()
    self.driver.find_element(By.CSS_SELECTOR, ".is-selectable:nth-child(6) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".b-numberinput .input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".b-numberinput .input").send_keys("20")
    self.driver.find_element(By.ID, "id_escola-nome_escola").click()
    self.driver.find_element(By.ID, "id_escola-nome_escola").send_keys("Judice Fialho")
    self.driver.find_element(By.ID, "id_escola-local").click()
    self.driver.find_element(By.ID, "id_escola-local").send_keys("Portimao")
    self.driver.find_element(By.ID, "id_escola-ano").click()
    self.driver.find_element(By.ID, "id_escola-ano").send_keys("12")
    self.driver.find_element(By.ID, "id_escola-turma").click()
    self.driver.find_element(By.ID, "id_escola-turma").send_keys("A")
    self.driver.find_element(By.ID, "id_escola-areacientifica").click()
    self.driver.find_element(By.ID, "id_escola-areacientifica").send_keys("Ciências e Tecnologia")
    element = self.driver.find_element(By.CSS_SELECTOR, ".b-numberinput .input")
    assert element.is_enabled() is True
    element = self.driver.find_element(By.NAME, "escola-dia")
    assert element.is_enabled() is True
    value = self.driver.find_element(By.ID, "id_escola-nome_escola").get_attribute("value")
    assert value == "Judice Fialho"
    value = self.driver.find_element(By.ID, "id_escola-areacientifica").get_attribute("value")
    assert value == "Ciências e Tecnologia"
    self.driver.find_element(By.CSS_SELECTOR, ".is-success > span:nth-child(1)").click()
  
