# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestStepresponsavel():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_stepresponsavel(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1918, 1027)
    self.driver.find_element(By.LINK_TEXT, "Criar Inscrição").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".button:nth-child(2) > span:nth-child(2)").text == "Escola (Turma)"
    self.driver.find_element(By.CSS_SELECTOR, ".button:nth-child(2) > span:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".is-success > span:nth-child(1)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".column:nth-child(1) .label").text == "Nome"
    assert self.driver.find_element(By.CSS_SELECTOR, ".column:nth-child(2) .label").text == "E-mail"
    element = self.driver.find_element(By.ID, "id_responsaveis-nome")
    assert element.is_enabled() is True
  
